name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: mariemmgh
          password: mariem123*

      - name: Build and Push Backend Image
        run: |
          docker build -t mariemmgh/gestiondesstocks-backend:latest ./app-blog
          docker push mariemmgh/gestiondesstocks-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t mariemmgh/gestiondesstocks-frontend:latest ./design-blog
          docker push mariemmgh/gestiondesstocks-frontend:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Apply Kubernetes Configuration
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/service.yaml
          kubectl apply -f app-blog/backend-deployment.yaml
          kubectl apply -f design-blog/frontend-deployment.yaml
          kubectl apply -f k8s/ingress.yaml
